services:
  api:
    build: .
    container_name: lapor-api
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0
    container_name: lapor-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lapor_db
      MYSQL_USER: lapor_user
      MYSQL_PASSWORD: lapor_password
    ports:
      - "9001:3306"
    volumes:
      - db_api_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lapor-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "9002:80"

volumes:
  db_api_data: